version: '3.8'

services:
  postgres:
    image: postgres
    container_name: postgres_sql
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - .env

  rabbitmq:
    image: "rabbitmq:3-management"
    container_name: rabbitmq
    restart: always
    ports:
      - "15672:15672"   # Interface de gerenciamento do RabbitMQ
      - "5672:5672"     # Porta do RabbitMQ para comunicação
    environment:
      RABBITMQ_DEFAULT_USER: ${QUEUE_USER}
      RABBITMQ_DEFAULT_PASS: ${QUEUE_PASSWORD}
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq
    env_file:
      - .env

volumes:
  postgres_data:
  rabbitmq-data: